### ISSUE TITLE
iteration1 warning about ambiguous names

### ISSUE THREAD

**Issue by jbrucker** [Ing140943/ku-polls#24]
When I run your iteration1 code (on main/master) it prints:

WARNINGS:
?: (urls.W005) URL namespace 'polls' isn't unique. You may not be able to reverse all URLs in this namespace

you should find the cause of this and fix it.

**Comment by Ing140943** [comment]
Thank you. Right now I can solve this issue. It happens because I have the same path in mysite directory and polls directory which is the same path. So I delete one of them to eliminate this problem. I fix it in the master branch because I already merge iteration1&2 to master for the latest assignment.
